obj-$(CONFIG_MACH_MSM8960_FX1) += board-fx1.o \
	board-fx1-camera.o \
	board-fx1-display.o \
	board-fx1-gpiomux.o \
	board-fx1-pmic.o \
	board-fx1-regulator.o \
	board-fx1-storage.o \
	board-fx1-misc.o \
	board-fx1-usb.o \
	board-fx1-sound.o \
	board-fx1-nfc.o \
	board-fx1-rfkill.o

obj-$(CONFIG_LGE_TOUCHSCREEN_CORE_325)+=board-fx1-input.o
obj-$(CONFIG_LGE_TOUCHSCREEN_CORE_f200)+=board-vu2-input.o