obj-$(CONFIG_MACH_MSM8960_L_DCM) += board-l_dcm.o \
	board-l_dcm-camera.o \
	board-l_dcm-display.o \
	board-l_dcm-gpiomux.o \
	board-l_dcm-pmic.o \
	board-l_dcm-regulator.o \
	board-l_dcm-storage.o \
	board-l_dcm-input.o \
	board-l_dcm-misc.o \
	board-l_dcm-usb.o \
	board-l_dcm-sound.o
