#
# Makefile for the broadcast(TDMB) RF/BB core.
#

obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= broadcast_tdmb_drv_if.o
#obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fc8050/
#obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= lg2102/
obj-$(CONFIG_LGE_BROADCAST_TDMB_T3900)		+= t3900/
#obj-$		+= t39fx/
#obj-y		+= broadcast_tdmb_drv_if.o
#obj-y		+= lg2102/
#obj-y		+= fc8050/
