obj-$(CONFIG_MACH_MSM8960_VU2) += board-vu2.o \
	board-vu2-camera.o \
	board-vu2-display.o \
	board-vu2-gpiomux.o \
	board-vu2-pmic.o \
	board-vu2-regulator.o \
	board-vu2-storage.o \
	board-vu2-misc.o \
	board-vu2-usb.o \
	board-vu2-sound.o \
	board-vu2-nfc.o \
	board-vu2-rfkill.o \
	board-vu2-input.o
