obj-$(CONFIG_MACH_MSM8960_L1) += board-l1.o \
	board-l1-camera.o \
	board-l1-display.o \
	board-l1-gpiomux.o \
	board-l1-pmic.o \
	board-l1-regulator.o \
	board-l1-storage.o \
	board-l1-input.o \
	board-l1-misc.o \
	board-l1-usb.o \
	board-l1-sound.o \
	board-l1-nfc.o \
	board-l1-rfkill.o
