obj-$(CONFIG_MACH_MSM8960_LX) += board-lx.o \
	board-lx-camera.o \
	board-lx-display.o \
	board-lx-gpiomux.o \
	board-lx-pmic.o \
	board-lx-regulator.o \
	board-lx-storage.o \
	board-lx-input.o \
	board-lx-misc.o \
	board-lx-usb.o \
	board-lx-nfc.o \
	board-lx-sound.o
